<?php

namespace Database\Seeders;

use Carbon\Carbon;
use DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('languages')->insert([
            ['name' => 'Abkhazian', 'iso_code' => 'abk', 'created_at' => Carbon::now(),],
            ['name' => 'Afar', 'iso_code' => 'aar', 'created_at' => Carbon::now(),],
            ['name' => 'Afrikaans', 'iso_code' => 'afr', 'created_at' => Carbon::now(),],
            ['name' => 'Akan', 'iso_code' => 'aka', 'created_at' => Carbon::now(),],
            ['name' => 'Fanti', 'iso_code' => 'fat', 'created_at' => Carbon::now(),],
            ['name' => 'Twi', 'iso_code' => 'twi', 'created_at' => Carbon::now(),],
            ['name' => 'Albanian', 'iso_code' => 'sqi', 'created_at' => Carbon::now(),],
            ['name' => 'Arbëreshë Albanian', 'iso_code' => 'aae', 'created_at' => Carbon::now(),],
            ['name' => 'Arvanitika Albanian', 'iso_code' => 'aat', 'created_at' => Carbon::now(),],
            ['name' => 'Gheg Albanian', 'iso_code' => 'aln', 'created_at' => Carbon::now(),],
            ['name' => 'Tosk Albanian', 'iso_code' => 'als', 'created_at' => Carbon::now(),],
            ['name' => 'Amharic', 'iso_code' => 'amh', 'created_at' => Carbon::now(),],
            ['name' => 'Arabic', 'iso_code' => 'ara', 'created_at' => Carbon::now(),],
            ['name' => 'Algerian Saharan Arabic', 'iso_code' => 'aao', 'created_at' => Carbon::now(),],
            ['name' => 'Tajiki Arabic', 'iso_code' => 'abh', 'created_at' => Carbon::now(),],
            ['name' => 'Baharna Arabic', 'iso_code' => 'abv', 'created_at' => Carbon::now(),],
            ['name' => 'Mesopotamian Arabic', 'iso_code' => 'acm', 'created_at' => Carbon::now(),],
            ['name' => 'Taizzi-Adeni Arabic', 'iso_code' => 'acq', 'created_at' => Carbon::now(),],
            ['name' => 'Hijazi Arabic', 'iso_code' => 'acw', 'created_at' => Carbon::now(),],
            ['name' => 'Omani Arabic', 'iso_code' => 'acx', 'created_at' => Carbon::now(),],
            ['name' => 'Cypriot Arabic', 'iso_code' => 'acy', 'created_at' => Carbon::now(),],
            ['name' => 'Dhofari Arabic', 'iso_code' => 'adf', 'created_at' => Carbon::now(),],
            ['name' => 'Tunisian Arabic', 'iso_code' => 'aeb', 'created_at' => Carbon::now(),],
            ['name' => 'Saidi Arabic', 'iso_code' => 'aec', 'created_at' => Carbon::now(),],
            ['name' => 'Gulf Arabic', 'iso_code' => 'afb', 'created_at' => Carbon::now(),],
            ['name' => 'Levantine Arabic', 'iso_code' => 'apc', 'created_at' => Carbon::now(),],
            ['name' => 'Sudanese Arabic', 'iso_code' => 'apd', 'created_at' => Carbon::now(),],
            ['name' => 'Standard Arabic', 'iso_code' => 'arb', 'created_at' => Carbon::now(),],
            ['name' => 'Algerian Arabic', 'iso_code' => 'arq', 'created_at' => Carbon::now(),],
            ['name' => 'Najdi Arabic', 'iso_code' => 'ars', 'created_at' => Carbon::now(),],
            ['name' => 'Moroccan Arabic', 'iso_code' => 'ary', 'created_at' => Carbon::now(),],
            ['name' => 'Egyptian Arabic', 'iso_code' => 'arz', 'created_at' => Carbon::now(),],
            ['name' => 'Uzbeki Arabic', 'iso_code' => 'auz', 'created_at' => Carbon::now(),],
            ['name' => 'Eastern Egyptian Bedawi Arabic', 'iso_code' => 'avl', 'created_at' => Carbon::now(),],
            ['name' => 'Hadrami Arabic', 'iso_code' => 'ayh', 'created_at' => Carbon::now(),],
            ['name' => 'Libyan Arabic', 'iso_code' => 'ayl', 'created_at' => Carbon::now(),],
            ['name' => 'Sanaani Arabic', 'iso_code' => 'ayn', 'created_at' => Carbon::now(),],
            ['name' => 'North Mesopotamian Arabic', 'iso_code' => 'ayp', 'created_at' => Carbon::now(),],
            ['name' => 'Sudanese Creole Arabic', 'iso_code' => 'pga', 'created_at' => Carbon::now(),],
            ['name' => 'Chadian Arabic', 'iso_code' => 'shu', 'created_at' => Carbon::now(),],
            ['name' => 'Shihhi Arabic', 'iso_code' => 'ssh', 'created_at' => Carbon::now(),],
            ['name' => 'Aragonese', 'iso_code' => 'arg', 'created_at' => Carbon::now(),],
            ['name' => 'Armenian', 'iso_code' => 'hye', 'created_at' => Carbon::now(),],
            ['name' => 'Assamese', 'iso_code' => 'asm', 'created_at' => Carbon::now(),],
            ['name' => 'Avaric', 'iso_code' => 'ava', 'created_at' => Carbon::now(),],
            ['name' => 'Avestan', 'iso_code' => 'ave', 'created_at' => Carbon::now(),],
            ['name' => 'Aymara', 'iso_code' => 'aym', 'created_at' => Carbon::now(),],
            ['name' => 'Southern Aymara', 'iso_code' => 'ayc', 'created_at' => Carbon::now(),],
            ['name' => 'Central Aymara', 'iso_code' => 'ayr', 'created_at' => Carbon::now(),],
            ['name' => 'Azerbaijani', 'iso_code' => 'aze', 'created_at' => Carbon::now(),],
            ['name' => 'South Azerbaijani', 'iso_code' => 'azb', 'created_at' => Carbon::now(),],
            ['name' => 'North Azerbaijani', 'iso_code' => 'azj', 'created_at' => Carbon::now(),],
            ['name' => 'Bambara', 'iso_code' => 'bam', 'created_at' => Carbon::now(),],
            ['name' => 'Bashkir', 'iso_code' => 'bak', 'created_at' => Carbon::now(),],
            ['name' => 'Basque', 'iso_code' => 'eus', 'created_at' => Carbon::now(),],
            ['name' => 'Belarusian', 'iso_code' => 'bel', 'created_at' => Carbon::now(),],
            ['name' => 'Bengali', 'iso_code' => 'ben', 'created_at' => Carbon::now(),],
            ['name' => 'Bislama', 'iso_code' => 'bis', 'created_at' => Carbon::now(),],
            ['name' => 'Bosnian', 'iso_code' => 'bos', 'created_at' => Carbon::now(),],
            ['name' => 'Breton', 'iso_code' => 'bre', 'created_at' => Carbon::now(),],
            ['name' => 'Bulgarian', 'iso_code' => 'bul', 'created_at' => Carbon::now(),],
            ['name' => 'Burmese', 'iso_code' => 'mya', 'created_at' => Carbon::now(),],
            ['name' => 'Catalan, Valencian', 'iso_code' => 'cat', 'created_at' => Carbon::now(),],
            ['name' => 'Chamorro', 'iso_code' => 'cha', 'created_at' => Carbon::now(),],
            ['name' => 'Chechen', 'iso_code' => 'che', 'created_at' => Carbon::now(),],
            ['name' => 'Chichewa, Chewa, Nyanja', 'iso_code' => 'nya', 'created_at' => Carbon::now(),],
            ['name' => 'Chinese', 'iso_code' => 'zho', 'created_at' => Carbon::now(),],
            ['name' => 'Min Dong Chinese', 'iso_code' => 'cdo', 'created_at' => Carbon::now(),],
            ['name' => 'Jinyu Chinese', 'iso_code' => 'cjy', 'created_at' => Carbon::now(),],
            ['name' => 'Mandarin Chinese', 'iso_code' => 'cmn', 'created_at' => Carbon::now(),],
            ['name' => 'Northern Ping Chinese', 'iso_code' => 'cnp', 'created_at' => Carbon::now(),],
            ['name' => 'Pu-Xian Chinese', 'iso_code' => 'cpx', 'created_at' => Carbon::now(),],
            ['name' => 'Southern Ping Chinese', 'iso_code' => 'csp', 'created_at' => Carbon::now(),],
            ['name' => 'Huizhou Chinese', 'iso_code' => 'czh', 'created_at' => Carbon::now(),],
            ['name' => 'Min Zhong Chinese', 'iso_code' => 'czo', 'created_at' => Carbon::now(),],
            ['name' => 'Gan Chinese', 'iso_code' => 'gan', 'created_at' => Carbon::now(),],
            ['name' => 'Hakka Chinese', 'iso_code' => 'hak', 'created_at' => Carbon::now(),],
            ['name' => 'Hainanese', 'iso_code' => 'hnm', 'created_at' => Carbon::now(),],
            ['name' => 'Xiang Chinese', 'iso_code' => 'hsn', 'created_at' => Carbon::now(),],
            ['name' => 'Leizhou Chinese', 'iso_code' => 'luh', 'created_at' => Carbon::now(),],
            ['name' => 'Literary Chinese', 'iso_code' => 'lzh', 'created_at' => Carbon::now(),],
            ['name' => 'Min Bei Chinese', 'iso_code' => 'mnp', 'created_at' => Carbon::now(),],
            ['name' => 'Min Nan Chinese', 'iso_code' => 'nan', 'created_at' => Carbon::now(),],
            ['name' => 'Shaojiang Chinese', 'iso_code' => 'sjc', 'created_at' => Carbon::now(),],
            ['name' => 'Wu Chinese', 'iso_code' => 'wuu', 'created_at' => Carbon::now(),],
            ['name' => 'Yue Chinese', 'iso_code' => 'yue', 'created_at' => Carbon::now(),],
            ['name' => 'Church Slavonic, Old Slavonic, Old Church Slavonic', 'iso_code' => 'chu', 'created_at' => Carbon::now(),],
            ['name' => 'Chuvash', 'iso_code' => 'chv', 'created_at' => Carbon::now(),],
            ['name' => 'Cornish', 'iso_code' => 'cor', 'created_at' => Carbon::now(),],
            ['name' => 'Corsican', 'iso_code' => 'cos', 'created_at' => Carbon::now(),],
            ['name' => 'Cree', 'iso_code' => 'cre', 'created_at' => Carbon::now(),],
            ['name' => 'Southern East Cree', 'iso_code' => 'crj', 'created_at' => Carbon::now(),],
            ['name' => 'Plains Cree', 'iso_code' => 'crk', 'created_at' => Carbon::now(),],
            ['name' => 'Northern East Cree', 'iso_code' => 'crl', 'created_at' => Carbon::now(),],
            ['name' => 'Moose Cree', 'iso_code' => 'crm', 'created_at' => Carbon::now(),],
            ['name' => 'Swampy Cree', 'iso_code' => 'csw', 'created_at' => Carbon::now(),],
            ['name' => 'Woods Cree', 'iso_code' => 'cwd', 'created_at' => Carbon::now(),],
            ['name' => 'Croatian', 'iso_code' => 'hrv', 'created_at' => Carbon::now(),],
            ['name' => 'Czech', 'iso_code' => 'ces', 'created_at' => Carbon::now(),],
            ['name' => 'Danish', 'iso_code' => 'dan', 'created_at' => Carbon::now(),],
            ['name' => 'Divehi, Dhivehi, Maldivian', 'iso_code' => 'div', 'created_at' => Carbon::now(),],
            ['name' => 'Dutch, Flemish', 'iso_code' => 'nld', 'created_at' => Carbon::now(),],
            ['name' => 'Dzongkha', 'iso_code' => 'dzo', 'created_at' => Carbon::now(),],
            ['name' => 'English', 'iso_code' => 'eng', 'created_at' => Carbon::now(),],
            ['name' => 'Esperanto', 'iso_code' => 'epo', 'created_at' => Carbon::now(),],
            ['name' => 'Estonian', 'iso_code' => 'est', 'created_at' => Carbon::now(),],
            ['name' => 'Standard Estonian', 'iso_code' => 'ekk', 'created_at' => Carbon::now(),],
            ['name' => 'Võro', 'iso_code' => 'vro', 'created_at' => Carbon::now(),],
            ['name' => 'Ewe', 'iso_code' => 'ewe', 'created_at' => Carbon::now(),],
            ['name' => 'Faroese', 'iso_code' => 'fao', 'created_at' => Carbon::now(),],
            ['name' => 'Fijian', 'iso_code' => 'fij', 'created_at' => Carbon::now(),],
            ['name' => 'Finnish', 'iso_code' => 'fin', 'created_at' => Carbon::now(),],
            ['name' => 'French', 'iso_code' => 'fra', 'created_at' => Carbon::now(),],
            ['name' => 'Western Frisian', 'iso_code' => 'fry', 'created_at' => Carbon::now(),],
            ['name' => 'Fulah', 'iso_code' => 'ful', 'created_at' => Carbon::now(),],
            ['name' => 'Maasina Fulfulde', 'iso_code' => 'ffm', 'created_at' => Carbon::now(),],
            ['name' => 'Adamawa Fulfulde', 'iso_code' => 'fub', 'created_at' => Carbon::now(),],
            ['name' => 'Pulaar', 'iso_code' => 'fuc', 'created_at' => Carbon::now(),],
            ['name' => 'Borgu Fulfulde', 'iso_code' => 'fue', 'created_at' => Carbon::now(),],
            ['name' => 'Pular', 'iso_code' => 'fuf', 'created_at' => Carbon::now(),],
            ['name' => 'Western Niger Fulfulde', 'iso_code' => 'fuh', 'created_at' => Carbon::now(),],
            ['name' => 'Bagirmi Fulfulde', 'iso_code' => 'fui', 'created_at' => Carbon::now(),],
            ['name' => 'Central-Eastern Niger Fulfulde', 'iso_code' => 'fuq', 'created_at' => Carbon::now(),],
            ['name' => 'Nigerian Fulfulde', 'iso_code' => 'fuv', 'created_at' => Carbon::now(),],
            ['name' => 'Gaelic, Scottish Gaelic', 'iso_code' => 'gla', 'created_at' => Carbon::now(),],
            ['name' => 'Galician', 'iso_code' => 'glg', 'created_at' => Carbon::now(),],
            ['name' => 'Ganda', 'iso_code' => 'lug', 'created_at' => Carbon::now(),],
            ['name' => 'Georgian', 'iso_code' => 'kat', 'created_at' => Carbon::now(),],
            ['name' => 'German', 'iso_code' => 'deu', 'created_at' => Carbon::now(),],
            ['name' => 'Greek, Modern', 'iso_code' => 'ell', 'created_at' => Carbon::now(),],
            ['name' => 'Kalaallisut, Greenlandic', 'iso_code' => 'kal', 'created_at' => Carbon::now(),],
            ['name' => 'Guarani', 'iso_code' => 'grn', 'created_at' => Carbon::now(),],
            ['name' => 'Western Bolivian Guaraní', 'iso_code' => 'gnw', 'created_at' => Carbon::now(),],
            ['name' => 'Paraguayan Guaraní', 'iso_code' => 'gug', 'created_at' => Carbon::now(),],
            ['name' => 'Eastern Bolivian Guaraní', 'iso_code' => 'gui', 'created_at' => Carbon::now(),],
            ['name' => 'Mbyá Guaraní', 'iso_code' => 'gun', 'created_at' => Carbon::now(),],
            ['name' => 'Chiripá', 'iso_code' => 'nhd', 'created_at' => Carbon::now(),],
            ['name' => 'Gujarati', 'iso_code' => 'guj', 'created_at' => Carbon::now(),],
            ['name' => 'Haitian, Haitian Creole', 'iso_code' => 'hat', 'created_at' => Carbon::now(),],
            ['name' => 'Hausa', 'iso_code' => 'hau', 'created_at' => Carbon::now(),],
            ['name' => 'Hebrew', 'iso_code' => 'heb', 'created_at' => Carbon::now(),],
            ['name' => 'Herero', 'iso_code' => 'her', 'created_at' => Carbon::now(),],
            ['name' => 'Hindi', 'iso_code' => 'hin', 'created_at' => Carbon::now(),],
            ['name' => 'Hiri Motu', 'iso_code' => 'hmo', 'created_at' => Carbon::now(),],
            ['name' => 'Hungarian', 'iso_code' => 'hun', 'created_at' => Carbon::now(),],
            ['name' => 'Icelandic', 'iso_code' => 'isl', 'created_at' => Carbon::now(),],
            ['name' => 'Ido', 'iso_code' => 'ido', 'created_at' => Carbon::now(),],
            ['name' => 'Igbo', 'iso_code' => 'ibo', 'created_at' => Carbon::now(),],
            ['name' => 'Indonesian', 'iso_code' => 'ind', 'created_at' => Carbon::now(),],
            ['name' => 'Interlingua (International Auxiliary Language Association)', 'iso_code' => 'ina', 'created_at' => Carbon::now(),],
            ['name' => 'Interlingue, Occidental', 'iso_code' => 'ile', 'created_at' => Carbon::now(),],
            ['name' => 'Inuktitut', 'iso_code' => 'iku', 'created_at' => Carbon::now(),],
            ['name' => 'Eastern Canadian Inuktitut', 'iso_code' => 'ike', 'created_at' => Carbon::now(),],
            ['name' => 'Inuinnaqtun', 'iso_code' => 'ikt', 'created_at' => Carbon::now(),],
            ['name' => 'Inupiaq', 'iso_code' => 'ipk', 'created_at' => Carbon::now(),],
            ['name' => 'North Alaskan Inupiatun', 'iso_code' => 'esi', 'created_at' => Carbon::now(),],
            ['name' => 'Northwest Alaska Inupiatun', 'iso_code' => 'esk', 'created_at' => Carbon::now(),],
            ['name' => 'Irish', 'iso_code' => 'gle', 'created_at' => Carbon::now(),],
            ['name' => 'Italian', 'iso_code' => 'ita', 'created_at' => Carbon::now(),],
            ['name' => 'Japanese', 'iso_code' => 'jpn', 'created_at' => Carbon::now(),],
            ['name' => 'Javanese', 'iso_code' => 'jav', 'created_at' => Carbon::now(),],
            ['name' => 'Kannada', 'iso_code' => 'kan', 'created_at' => Carbon::now(),],
            ['name' => 'Kanuri', 'iso_code' => 'kau', 'created_at' => Carbon::now(),],
            ['name' => 'Manga Kanuri', 'iso_code' => 'kby', 'created_at' => Carbon::now(),],
            ['name' => 'Central Kanuri', 'iso_code' => 'knc', 'created_at' => Carbon::now(),],
            ['name' => 'Tumari Kanuri', 'iso_code' => 'krt', 'created_at' => Carbon::now(),],
            ['name' => 'Kashmiri', 'iso_code' => 'kas', 'created_at' => Carbon::now(),],
            ['name' => 'Kazakh', 'iso_code' => 'kaz', 'created_at' => Carbon::now(),],
            ['name' => 'Central Khmer', 'iso_code' => 'khm', 'created_at' => Carbon::now(),],
            ['name' => 'Kikuyu, Gikuyu', 'iso_code' => 'kik', 'created_at' => Carbon::now(),],
            ['name' => 'Kinyarwanda', 'iso_code' => 'kin', 'created_at' => Carbon::now(),],
            ['name' => 'Kyrgyz, Kirghiz', 'iso_code' => 'kir', 'created_at' => Carbon::now(),],
            ['name' => 'Komi', 'iso_code' => 'kom', 'created_at' => Carbon::now(),],
            ['name' => 'Komi-Permyak', 'iso_code' => 'koi', 'created_at' => Carbon::now(),],
            ['name' => 'Komi-Zyrian', 'iso_code' => 'kpv', 'created_at' => Carbon::now(),],
            ['name' => 'Kongo', 'iso_code' => 'kon', 'created_at' => Carbon::now(),],
            ['name' => 'Koongo', 'iso_code' => 'kng', 'created_at' => Carbon::now(),],
            ['name' => 'San Salvador Kongo', 'iso_code' => 'kwy', 'created_at' => Carbon::now(),],
            ['name' => 'Laari', 'iso_code' => 'ldi', 'created_at' => Carbon::now(),],
            ['name' => 'Korean', 'iso_code' => 'kor', 'created_at' => Carbon::now(),],
            ['name' => 'Kuanyama, Kwanyama', 'iso_code' => 'kua', 'created_at' => Carbon::now(),],
            ['name' => 'Kurdish', 'iso_code' => 'kur', 'created_at' => Carbon::now(),],
            ['name' => 'Central Kurdish', 'iso_code' => 'ckb', 'created_at' => Carbon::now(),],
            ['name' => 'Northern Kurdish', 'iso_code' => 'kmr', 'created_at' => Carbon::now(),],
            ['name' => 'Southern Kurdish', 'iso_code' => 'sdh', 'created_at' => Carbon::now(),],
            ['name' => 'Lao', 'iso_code' => 'lao', 'created_at' => Carbon::now(),],
            ['name' => 'Latin', 'iso_code' => 'lat', 'created_at' => Carbon::now(),],
            ['name' => 'Latvian', 'iso_code' => 'lav', 'created_at' => Carbon::now(),],
            ['name' => 'Latgalian', 'iso_code' => 'ltg', 'created_at' => Carbon::now(),],
            ['name' => 'Standard Latvian', 'iso_code' => 'lvs', 'created_at' => Carbon::now(),],
            ['name' => 'Limburgan, Limburger, Limburgish', 'iso_code' => 'lim', 'created_at' => Carbon::now(),],
            ['name' => 'Lingala', 'iso_code' => 'lin', 'created_at' => Carbon::now(),],
            ['name' => 'Lithuanian', 'iso_code' => 'lit', 'created_at' => Carbon::now(),],
            ['name' => 'Luba-Katanga', 'iso_code' => 'lub', 'created_at' => Carbon::now(),],
            ['name' => 'Luxembourgish, Letzeburgesch', 'iso_code' => 'ltz', 'created_at' => Carbon::now(),],
            ['name' => 'Macedonian', 'iso_code' => 'mkd', 'created_at' => Carbon::now(),],
            ['name' => 'Malagasy', 'iso_code' => 'mlg', 'created_at' => Carbon::now(),],
            ['name' => 'Bara Malagasy', 'iso_code' => 'bhr', 'created_at' => Carbon::now(),],
            ['name' => 'Northern Betsimisaraka Malagasy', 'iso_code' => 'bmm', 'created_at' => Carbon::now(),],
            ['name' => 'Southern Betsimisaraka Malagasy', 'iso_code' => 'bzc', 'created_at' => Carbon::now(),],
            ['name' => 'Masikoro Malagasy', 'iso_code' => 'msh', 'created_at' => Carbon::now(),],
            ['name' => 'Plateau Malagasy', 'iso_code' => 'plt', 'created_at' => Carbon::now(),],
            ['name' => 'Sakalava Malagasy', 'iso_code' => 'skg', 'created_at' => Carbon::now(),],
            ['name' => 'Tandroy-Mahafaly Malagasy', 'iso_code' => 'tdx', 'created_at' => Carbon::now(),],
            ['name' => 'Tesaka Malagasy', 'iso_code' => 'tkg ', 'created_at' => Carbon::now(),],
            ['name' => 'Tanosy Malagasy', 'iso_code' => 'txy', 'created_at' => Carbon::now(),],
            ['name' => 'Antankarana Malagasy', 'iso_code' => 'xmv', 'created_at' => Carbon::now(),],
            ['name' => 'Tsimihety Malagasy', 'iso_code' => 'xmw', 'created_at' => Carbon::now(),],
            ['name' => 'Malay', 'iso_code' => 'msa', 'created_at' => Carbon::now(),],
            ['name' => 'Malayalam', 'iso_code' => 'mal', 'created_at' => Carbon::now(),],
            ['name' => 'Maltese', 'iso_code' => 'mlt', 'created_at' => Carbon::now(),],
            ['name' => 'Manx', 'iso_code' => 'glv', 'created_at' => Carbon::now(),],
            ['name' => 'Maori', 'iso_code' => 'mri', 'created_at' => Carbon::now(),],
            ['name' => 'Marathi', 'iso_code' => 'mar', 'created_at' => Carbon::now(),],
            ['name' => 'Marshallese', 'iso_code' => 'mah', 'created_at' => Carbon::now(),],
            ['name' => 'Mongolian', 'iso_code' => 'mon', 'created_at' => Carbon::now(),],
            ['name' => 'Nauru', 'iso_code' => 'nau', 'created_at' => Carbon::now(),],
            ['name' => 'Navajo, Navaho', 'iso_code' => 'nav', 'created_at' => Carbon::now(),],
            ['name' => 'North Ndebele', 'iso_code' => 'nde', 'created_at' => Carbon::now(),],
            ['name' => 'South Ndebele', 'iso_code' => 'nbl', 'created_at' => Carbon::now(),],
            ['name' => 'Ndonga', 'iso_code' => 'ndo', 'created_at' => Carbon::now(),],
            ['name' => 'Nepali', 'iso_code' => 'nep', 'created_at' => Carbon::now(),],
            ['name' => 'Norwegian', 'iso_code' => 'nor', 'created_at' => Carbon::now(),],
            ['name' => 'Norwegian Bokmål', 'iso_code' => 'nob', 'created_at' => Carbon::now(),],
            ['name' => 'Norwegian Nynorsk', 'iso_code' => 'nno', 'created_at' => Carbon::now(),],
            ['name' => 'Occitan', 'iso_code' => 'oci', 'created_at' => Carbon::now(),],
            ['name' => 'Ojibwa', 'iso_code' => 'oji', 'created_at' => Carbon::now(),],
            ['name' => 'Oriya', 'iso_code' => 'ori', 'created_at' => Carbon::now(),],
            ['name' => 'Oromo', 'iso_code' => 'orm', 'created_at' => Carbon::now(),],
            ['name' => 'Ossetian, Ossetic', 'iso_code' => 'oss', 'created_at' => Carbon::now(),],
            ['name' => 'Pali', 'iso_code' => 'pli', 'created_at' => Carbon::now(),],
            ['name' => 'Pashto, Pushto', 'iso_code' => 'pus', 'created_at' => Carbon::now(),],
            ['name' => 'Persian', 'iso_code' => 'fas', 'created_at' => Carbon::now(),],
            ['name' => 'Polish', 'iso_code' => 'pol', 'created_at' => Carbon::now(),],
            ['name' => 'Portuguese', 'iso_code' => 'por', 'created_at' => Carbon::now(),],
            ['name' => 'Punjabi, Panjabi', 'iso_code' => 'pan', 'created_at' => Carbon::now(),],
            ['name' => 'Quechua', 'iso_code' => 'que', 'created_at' => Carbon::now(),],
            ['name' => 'Romanian, Moldavian, Moldovan', 'iso_code' => 'ron', 'created_at' => Carbon::now(),],
            ['name' => 'Romansh', 'iso_code' => 'roh', 'created_at' => Carbon::now(),],
            ['name' => 'Rundi', 'iso_code' => 'run', 'created_at' => Carbon::now(),],
            ['name' => 'Russian', 'iso_code' => 'rus', 'created_at' => Carbon::now(),],
            ['name' => 'Northern Sami', 'iso_code' => 'sme', 'created_at' => Carbon::now(),],
            ['name' => 'Samoan', 'iso_code' => 'smo', 'created_at' => Carbon::now(),],
            ['name' => 'Sango', 'iso_code' => 'sag', 'created_at' => Carbon::now(),],
            ['name' => 'Sanskrit', 'iso_code' => 'san', 'created_at' => Carbon::now(),],
            ['name' => 'Sardinian', 'iso_code' => 'srd', 'created_at' => Carbon::now(),],
            ['name' => 'Serbian', 'iso_code' => 'srp', 'created_at' => Carbon::now(),],
            ['name' => 'Shona', 'iso_code' => 'sna', 'created_at' => Carbon::now(),],
            ['name' => 'Sindhi', 'iso_code' => 'snd', 'created_at' => Carbon::now(),],
            ['name' => 'Sinhala, Sinhalese', 'iso_code' => 'sin', 'created_at' => Carbon::now(),],
            ['name' => 'Slovak', 'iso_code' => 'slk', 'created_at' => Carbon::now(),],
            ['name' => 'Slovenian', 'iso_code' => 'slv', 'created_at' => Carbon::now(),],
            ['name' => 'Somali', 'iso_code' => 'som', 'created_at' => Carbon::now(),],
            ['name' => 'Southern Sotho', 'iso_code' => 'sot', 'created_at' => Carbon::now(),],
            ['name' => 'Spanish, Castilian', 'iso_code' => 'spa', 'created_at' => Carbon::now(),],
            ['name' => 'Sundanese', 'iso_code' => 'sun', 'created_at' => Carbon::now(),],
            ['name' => 'Swahili', 'iso_code' => 'swa', 'created_at' => Carbon::now(),],
            ['name' => 'Swati', 'iso_code' => 'ssw', 'created_at' => Carbon::now(),],
            ['name' => 'Swedish', 'iso_code' => 'swe', 'created_at' => Carbon::now(),],
            ['name' => 'Tagalog', 'iso_code' => 'tgl', 'created_at' => Carbon::now(),],
            ['name' => 'Tahitian', 'iso_code' => 'tah', 'created_at' => Carbon::now(),],
            ['name' => 'Tajik', 'iso_code' => 'tgk', 'created_at' => Carbon::now(),],
            ['name' => 'Tamil', 'iso_code' => 'tam', 'created_at' => Carbon::now(),],
            ['name' => 'Tatar', 'iso_code' => 'tat', 'created_at' => Carbon::now(),],
            ['name' => 'Telugu', 'iso_code' => 'tel', 'created_at' => Carbon::now(),],
            ['name' => 'Thai', 'iso_code' => 'tha', 'created_at' => Carbon::now(),],
            ['name' => 'Tibetan', 'iso_code' => 'bod', 'created_at' => Carbon::now(),],
            ['name' => 'Tigrinya', 'iso_code' => 'tir', 'created_at' => Carbon::now(),],
            ['name' => 'Tonga (Tonga Islands)', 'iso_code' => 'ton', 'created_at' => Carbon::now(),],
            ['name' => 'Tsonga', 'iso_code' => 'tso', 'created_at' => Carbon::now(),],
            ['name' => 'Tswana', 'iso_code' => 'tsn', 'created_at' => Carbon::now(),],
            ['name' => 'Turkish', 'iso_code' => 'tur', 'created_at' => Carbon::now(),],
            ['name' => 'Turkmen', 'iso_code' => 'tuk', 'created_at' => Carbon::now(),],
            ['name' => 'Uighur, Uyghur', 'iso_code' => 'uig', 'created_at' => Carbon::now(),],
            ['name' => 'Ukrainian', 'iso_code' => 'ukr', 'created_at' => Carbon::now(),],
            ['name' => 'Urdu', 'iso_code' => 'urd', 'created_at' => Carbon::now(),],
            ['name' => 'Uzbek', 'iso_code' => 'uzb', 'created_at' => Carbon::now(),],
            ['name' => 'Venda', 'iso_code' => 'ven', 'created_at' => Carbon::now(),],
            ['name' => 'Vietnamese', 'iso_code' => 'vie', 'created_at' => Carbon::now(),],
            ['name' => 'Volapük', 'iso_code' => 'vol', 'created_at' => Carbon::now(),],
            ['name' => 'Walloon', 'iso_code' => 'wln', 'created_at' => Carbon::now(),],
            ['name' => 'Welsh', 'iso_code' => 'cym', 'created_at' => Carbon::now(),],
            ['name' => 'Wolof', 'iso_code' => 'wol', 'created_at' => Carbon::now(),],
            ['name' => 'Xhosa', 'iso_code' => 'xho', 'created_at' => Carbon::now(),],
            ['name' => 'Sichuan Yi, Nuosu', 'iso_code' => 'iii', 'created_at' => Carbon::now(),],
            ['name' => 'Yiddish', 'iso_code' => 'yid', 'created_at' => Carbon::now(),],
            ['name' => 'Yoruba', 'iso_code' => 'yor', 'created_at' => Carbon::now(),],
            ['name' => 'Zhuang, Chuang', 'iso_code' => 'zha', 'created_at' => Carbon::now(),],
            ['name' => 'Zulu', 'iso_code' => 'zul', 'created_at' => Carbon::now(),],
        ]);
    }
}
